services:
  wallet-watchguard:
    image: ghcr.io/xannythepleb/bitcoin-wallet-watchguard:latest
    #user: "${WWG_UID:-10001}:${WWG_GID:-10001}"
    container_name: wallet-watchguard
    restart: unless-stopped
    environment:
      # Needed only for `wwg run`, not for `wwg init`.
      # Do not commit this. Prefer a local .env file outside git.
      WWG_PASSPHRASE: ${WWG_PASSPHRASE:-}
      # Optional: set to true to enable the internal Tor upstream.
      # You can also use tor.enabled: true in config.yaml.
      WWG_TOR_UPSTREAM: ${WWG_TOR_UPSTREAM:-false}
      # Keep config and db in a Docker volume with a single variable
      # Avoids ownership and permissions issues with Docker & SQLite
      # Also makes this shit easier to maintain
      WWG_DATA_DIR: /app/data
    volumes:
      #- ./data:/app/data
      - wwg-data:/app/data

volumes:
  wwg-data:
    name: wwg-data